###########
# site.title

title:    'SpartaCraft'
subtitle: 'CS 175: Project in AI (in Minecraft)'


#########################
# more settings

markdown: kramdown

mathjax: True

exclude:
- README.md
- LICENSE.md
- Gemfile
- Gemfile.lock
